config/routes.rb
Rails.application.routes.draw do
  get "/", to: "hot_takes#index"

  resources :hot_takes, only: [:index, :create]
  resources :turbo_for_free_hot_takes, only: [:index, :create]
  resources :turbo_optimized_hot_takes, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hot_take.rb
class HotTake < ApplicationRecord
  validates_presence_of :handle
  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hot_takes_controller.rb
class HotTakesController < ApplicationController
  # GET /hot_takes
  def index
    @hot_takes = HotTake.all
    @hot_take = HotTake.new
  end

  # POST /hot_takes
  def create
    @hot_take = HotTake.new(hot_take_params)

    if @hot_take.save
      redirect_to hot_takes_path
    else
      @hot_takes = HotTake.all
      render :index
    end
  end

  private
    def hot_take_params
      params.require(:hot_take).permit(:handle, :content)
    end
end

app/controllers/turbo_for_free_hot_takes_controller.rb
class TurboForFreeHotTakesController < ApplicationController
  # GET /hot_takes
  def index
    @hot_takes = HotTake.all
    @hot_take = HotTake.new
  end

  # POST /hot_takes
  def create
    @hot_take = HotTake.new(hot_take_params)

    if @hot_take.save
      redirect_to turbo_for_free_hot_takes_path
    else
      @hot_takes = HotTake.all
      render :index
    end
  end

  private
    def hot_take_params
      params.require(:hot_take).permit(:handle, :content)
    end
end

app/controllers/turbo_optimized_hot_takes_controller.rb
class TurboOptimizedHotTakesController < ApplicationController
  # GET /hot_takes
  def index
    @hot_takes = HotTake.all
    @hot_take = HotTake.new
  end

  # POST /hot_takes
  def create
    @hot_take = HotTake.new(hot_take_params)

    if @hot_take.save
      append_new_row_update = turbo_stream.append(
        :hot_takes_list,
        partial: "hot_take_item",
        locals: { hot_take: @hot_take }
      )

      replace_form_update = turbo_stream.replace(
        :hot_take_form,
        partial: "form",
        locals: { hot_take: HotTake.new },
      )

      render(turbo_stream: [
        append_new_row_update,
        replace_form_update,
      ])
    else
      replace_form_update = turbo_stream.replace(
        :hot_take_form,
        partial: "form",
        locals: { hot_take: @hot_take }
      )

      render(turbo_stream: replace_form_update)
    end
  end

  private
    def hot_take_params
      params.require(:hot_take).permit(:handle, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hot_takes_helper.rb
module HotTakesHelper
end

app/views/hot_takes/_form.html.erb
<%= form_with(model: hot_take) do |form| %>
  <% if hot_take.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hot_take.errors.count, "error") %> prohibited this hot_take from being saved:</h2>

      <ul>
        <% hot_take.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handle %>
    <%= form.text_field :handle %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hot_takes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hot Takes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hot_takes.each do |hot_take| %>
      <tr>
        <td><%= hot_take.handle %></td>
        <td><%= hot_take.content %></td>
        <td><%= hot_take.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>New Hot Take</h1>
<%= render 'form', hot_take: @hot_take %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stimulus_include_tags %>
    <%= javascript_include_tag "turbo", type: "module-shim" %>
    <%= yield :head %>
  </head>

  <body>
    <div>
      <%= link_to "Regular hot takes", hot_takes_path %>
      <%= link_to "Turbo for free hot takes", turbo_for_free_hot_takes_path %>
      <%= link_to "Turbo optimized hot takes", turbo_optimized_hot_takes_path %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/turbo_for_free_hot_takes/_form.html.erb
<%= form_with(model: hot_take, url: turbo_for_free_hot_takes_path) do |form| %>
  <% if hot_take.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hot_take.errors.count, "error") %> prohibited this hot_take from being saved:</h2>

      <ul>
        <% hot_take.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handle %>
    <%= form.text_field :handle %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turbo_for_free_hot_takes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Turbo for free Hot Takes</h1>

<p>
  Page loaded at <%= Time.now %>
</p>

<turbo-frame id="hot_takes">
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @hot_takes.each do |hot_take| %>
        <tr>
          <td><%= hot_take.handle %></td>
          <td><%= hot_take.content %></td>
          <td><%= hot_take.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <h1>New Hot Take</h1>
  <%= render 'form', hot_take: @hot_take %>
</turbo-frame>

app/views/turbo_optimized_hot_takes/_form.html.erb
<%= form_with(model: hot_take, url: turbo_optimized_hot_takes_path) do |form| %>
  <% if hot_take.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hot_take.errors.count, "error") %> prohibited this hot_take from being saved:</h2>

      <ul>
        <% hot_take.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handle %>
    <%= form.text_field :handle %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/turbo_optimized_hot_takes/_hot_take_item.html.erb
<li style="padding-bottom: 10px">
  <%= hot_take.handle %>: <td><%= hot_take.content %></td>
  <br />
  <%= hot_take.created_at %>
</li>

app/views/turbo_optimized_hot_takes/index.html.erb
<h1>Turbo optimized Hot Takes</h1>

<p>
  Page loaded at <%= Time.now %>
</p>

<ul>
  <turbo-frame id="hot_takes_list">
    <% @hot_takes.each do |hot_take| %>
      <%= render partial: "hot_take_item", locals: { hot_take: hot_take } %>
    <% end %>
  </turbo-frame>
</ul>

<br>

<h1>New Hot Take</h1>
<turbo-frame id="hot_take_form">
  <%= render 'form', hot_take: @hot_take %>
</turbo-frame>